### ISSUE TITLE
Eldritch blast doing half damage with the "powerful cantrip" feat when 1 blast misses

### ISSUE THREAD

**Issue by SemBerretty** [Holic75/SolastaWarlockClass#2]
I've taken the powerful cantrip feat on my warlock which makes it so you'll do half damage on a miss instead of none.

The issue is that when my warlock fires 2 eldritch blasts and one of the attacks misses, both blasts will only deal half damage no matter if the other one hits or not.

Screenshot included where my crit eldritch blast deals half damage.

![SolastaWarlockBug](https://user-images.githubusercontent.com/16963487/126912779-a6d0dc5c-7afc-490f-b2a4-4ad237f7a83e.png)

**Comment by Holic75** [comment]
fixed by SolastaModHelpers 0.9.11
